ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://github.com/rofl0r/microsocks/archive/refs/tags/v1.0.3.tar.gz source.tar.gz 6801559b6f8e17240ed8eef17a36eea8643412b5a7476980fd4e24b02a021b82 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd microsocks-* && \
echo 'prefix = /output\nbindir = $(prefix)\n' > config.mak && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse -Os -s -fno-ident -fno-asynchronous-unwind-tables" \
LDFLAGS="-static" \
make -j$(nproc) && \
make install

CMD bash
