ARG MUSL_TARGET=x86_64-linux-musl
FROM debian:bullseye
ARG MUSL_TARGET

RUN mkdir /output && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates wget tar xz-utils && \
    apt-get clean

RUN mkdir -p /build && cd /build && \
    wget -qO- https://musl.cc/${MUSL_TARGET}-cross.tgz | tar xz && \
    mv ${MUSL_TARGET}-cross cross

CMD ["bash"]
