ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.0/e2fsprogs-1.47.0.tar.gz source.tar.gz 0b4fe723d779b0927fb83c9ae709bc7b40f66d7df36433bef143e41c54257084 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd e2fsprogs-* && \
sed -e '/fallocate64/d' -i configure.ac && \
mkdir build && \
cd build && \
export CC="$MUSL_TARGET-gcc" && \
export CFLAGS="-static -frandom-seed=pulse" && \
export LDFLAGS=--static && \
../configure \
--host=$($MUSL_TARGET-gcc -dumpmachine) \
--prefix=/output && \
make -j$(nproc) && \
make install

CMD bash
