ARG MUSL_TARGET=x86_64-linux-musl
FROM openssl-1.1.1k-${MUSL_TARGET} AS openssl
FROM pcre-8.45-${MUSL_TARGET} AS pcre
FROM musl-cross-make-${MUSL_TARGET}
ARG MUSL_TARGET

COPY --from=openssl /output /output
COPY --from=pcre /output /output

WORKDIR /build
RUN download https://github.com/denandz/fuzzotron/archive/9e86436021a4adf344215c21892eee390a1d0469.tar.gz source.tar.gz 7b93c47c2382a9c6bc64a0d948b2c7bc9bef18556321fd0eeff041b45130733a && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd fuzzotron-* && \
sed -e 's/^LIBS = .*/LIBS = -lpcre -lssl -lcrypto -lpthread/' -i Makefile && \
CC="${MUSL_TARGET}-gcc -static -frandom-seed=pulse -I/output/include" \
LDFLAGS="-L/output/lib" \
make -j$(nproc) fuzzotron replay && \
mkdir -p /output/bin && \
cp replay /output/bin/replay && \ 
cp fuzzotron /output/bin/fuzzotron && \
$MUSL_TARGET-strip /output/bin/fuzzotron && \
$MUSL_TARGET-strip /output/bin/replay

CMD bash
