ARG MUSL_TARGET=x86_64-linux-musl
FROM musl-cross-make-$MUSL_TARGET
ARG MUSL_TARGET

WORKDIR /build
RUN download https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz source.tar.gz 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23 && tar xf source.tar.gz
RUN export PATH=/build/cross/bin:$PATH && \
cd zlib-* && \
CC="$MUSL_TARGET-gcc" \
CFLAGS="-static -frandom-seed=pulse" \
./configure \
--prefix=/output \
--static && \
make -j$(nproc) && \
make install

CMD bash
